name: CI

on: [push]
jobs:
  ci:
    name: runner-test
    runs-on: ec2-runner
    strategy:
      matrix:
        python-version: [ '3.8' ]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Install Pytest
      run: pip install pytest
        
    - name: Run test script
      run: pytest divide-tests.py
