name: CI

on: [push]
jobs:
  ci:
    name: runner-test
    runs-on: self-hosted
    strategy:
      matrix:
        python-version: [ '3.8' ]

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
      
    - name: Install Colorama
      run: pip install colorama
        
    - name: Run test script
      run: python action-test.py
